import { School, StoreItem, Student, Payment, NewsletterSubscriber } from "./types";

export const seedSchools: School[] = [
  {
    id: "sch-1",
    name: "Apex Model College",
    slug: "apex-college",
    address: "12 Allen Avenue, Ikeja, Lagos",
    phone: "+234 801 234 5678",
    email: "bursary@apexcollege.ng",
    principal: "Mrs. Funmi Adebayo",
    bankName: "Zenith Bank",
    accountNumber: "1012345678",
    accountName: "Apex Model College Ltd",
    paystackSubaccountCode: "ACCT_w74g823k190f",
    receiptFooter: "Official clearance receipt for Apex Model College. Retain for gate pass.",
    session: "2025/2026",
    term: "First Term",
    allowPartial: true,
    status: "Active",
    createdAt: "2025-01-10T00:00:00.000Z",
  },
  {
    id: "sch-2",
    name: "Crystal Heights Academy",
    slug: "crystal-heights",
    address: "Plot 402 Gwarinpa Estate, Abuja",
    phone: "+234 803 987 6543",
    email: "bursary@crystalheights.edu.ng",
    principal: "Dr. Emmanuel Okafor",
    bankName: "Guaranty Trust Bank",
    accountNumber: "0123456789",
    accountName: "Crystal Heights Academy",
    paystackSubaccountCode: "ACCT_9832hd8129fn",
    receiptFooter: "Official clearance receipt for Crystal Heights Academy.",
    session: "2025/2026",
    term: "First Term",
    allowPartial: false,
    status: "Active",
    createdAt: "2025-01-15T00:00:00.000Z",
  },
  {
    id: "sch-3",
    name: "Heritage International School",
    slug: "heritage-school",
    address: "15 Peter Odili Road, Port Harcourt",
    phone: "+234 805 111 2233",
    email: "accounts@heritageschool.ng",
    principal: "Mr. Tari Briggs",
    bankName: "Access Bank",
    accountNumber: "0987654321",
    accountName: "Heritage International Schools Ltd",
    paystackSubaccountCode: "ACCT_471928df7182",
    receiptFooter: "Knowledge and Excellence. Retain this slip for gate verification.",
    session: "2025/2026",
    term: "First Term",
    allowPartial: true,
    status: "Active",
    createdAt: "2025-02-01T00:00:00.000Z",
  },
];

export const seedStoreItems: StoreItem[] = [
  {
    id: "item-1",
    schoolId: "sch-1",
    title: "Senior Secondary Biology Practical Manual",
    category: "Textbook",
    amount: 4500,
    className: "SSS 1B",
    description: "Approved curriculum lab guide for WAEC preparation.",
    inStock: true,
  },
  {
    id: "item-2",
    schoolId: "sch-1",
    title: "Complete School Uniform Set (2 Pairs + Badge)",
    category: "Uniform",
    amount: 18000,
    className: "All",
    description: "High-grade durable fabric with embroidered school crest.",
    inStock: true,
  },
  {
    id: "item-3",
    schoolId: "sch-1",
    title: "National Heritage Excursion Ticket",
    category: "Excursion",
    amount: 15000,
    className: "JSS 2A",
    description: "Includes luxury transport, museum entry, and catered lunch.",
    inStock: true,
  },
  {
    id: "item-4",
    schoolId: "sch-1",
    title: "Inter-House Sports Jersey & Socks",
    category: "Uniform",
    amount: 6500,
    className: "All",
    description: "Official customized house colors sports outfit.",
    inStock: true,
  },
];

export const seedStudents: Student[] = [
  {
    id: "s1",
    schoolId: "sch-1",
    admissionNumber: "AMC/2025/001",
    name: "Chiamaka Okeke",
    className: "JSS 2A",
    parentName: "Mr. Chukwudi Okeke",
    parentPhone: "+2348011112222",
    parentEmail: "chiamaka.parent@gmail.com",
    fees: [
      { category: "Tuition", amount: 120000, title: "First Term Tuition" },
      { category: "Books", amount: 25000, title: "Curriculum Textbooks" },
      { category: "Uniform", amount: 15000, title: "School Uniform" },
    ],
    paid: 80000,
  },
  {
    id: "s2",
    schoolId: "sch-1",
    admissionNumber: "AMC/2025/002",
    name: "Tunde Bakare",
    className: "SSS 1B",
    parentName: "Mrs. Folashade Bakare",
    parentPhone: "+2348033334444",
    parentEmail: "folashade.b@yahoo.com",
    fees: [
      { category: "Tuition", amount: 150000, title: "First Term Tuition" },
      { category: "Exam", amount: 10000, title: "Term Exam Fee" },
      { category: "Boarding", amount: 90000, title: "Boarding House Levy" },
    ],
    paid: 0,
  },
  {
    id: "s3",
    schoolId: "sch-1",
    admissionNumber: "AMC/2025/003",
    name: "Aisha Mohammed",
    className: "Primary 5",
    parentName: "Alhaji Ibrahim Mohammed",
    parentPhone: "+2348055556666",
    fees: [
      { category: "Tuition", amount: 90000, title: "First Term Tuition" },
      { category: "Books", amount: 18000, title: "Textbooks Pack" },
      { category: "Transport", amount: 30000, title: "School Bus Service" },
    ],
    paid: 138000,
  },
  {
    id: "s4",
    schoolId: "sch-2",
    admissionNumber: "CHA/2025/101",
    name: "David Adeleke",
    className: "SSS 2",
    parentName: "Chief Adewale Adeleke",
    parentPhone: "+2348022223333",
    fees: [
      { category: "Tuition", amount: 220000, title: "First Term Tuition" },
      { category: "Exam", amount: 25000, title: "Laboratory & Exam Fee" },
    ],
    paid: 245000,
  },
  {
    id: "s5",
    schoolId: "sch-2",
    admissionNumber: "CHA/2025/102",
    name: "Ngozi Eze",
    className: "JSS 3",
    parentName: "Dr. Kalu Eze",
    parentPhone: "+2348044445555",
    fees: [
      { category: "Tuition", amount: 190000, title: "First Term Tuition" },
      { category: "Books", amount: 35000, title: "BECE Preparation Pack" },
    ],
    paid: 100000,
  },
];

export const seedPayments: Payment[] = [
  {
    id: "p1",
    receiptNumber: "RCPT-100001",
    schoolId: "sch-1",
    studentId: "s1",
    amount: 80000,
    items: [{ title: "First Term Tuition (Partial)", category: "Tuition", amount: 80000 }],
    method: "Card",
    reference: "TRX-AB12CD34",
    date: new Date(Date.now() - 86400000 * 3).toISOString(),
    payerEmail: "chiamaka.parent@gmail.com",
    status: "Successful",
  },
  {
    id: "p2",
    receiptNumber: "RCPT-100002",
    schoolId: "sch-1",
    studentId: "s3",
    amount: 138000,
    items: [
      { title: "First Term Tuition", category: "Tuition", amount: 90000 },
      { title: "Textbooks Pack", category: "Books", amount: 18000 },
      { title: "School Bus Service", category: "Transport", amount: 30000 },
    ],
    method: "Bank Transfer",
    reference: "TRX-EF56GH78",
    date: new Date(Date.now() - 86400000 * 10).toISOString(),
    status: "Successful",
  },
  {
    id: "p3",
    receiptNumber: "RCPT-100003",
    schoolId: "sch-2",
    studentId: "s4",
    amount: 245000,
    items: [
      { title: "First Term Tuition", category: "Tuition", amount: 220000 },
      { title: "Laboratory & Exam Fee", category: "Exam", amount: 25000 },
    ],
    method: "USSD",
    reference: "TRX-IJ90KL12",
    date: new Date(Date.now() - 86400000 * 18).toISOString(),
    status: "Successful",
  },
];

export const seedSubscribers: NewsletterSubscriber[] = [
  {
    id: "sub-1",
    schoolId: "sch-1",
    admissionNumber: "AMC/2025/001",
    guardianEmail: "chiamaka.parent@gmail.com",
    guardianPhone: "+2348011112222",
    createdAt: new Date(Date.now() - 86400000 * 12).toISOString(),
  },
];
